### ISSUE TITLE
encodeString in type_converter.dart

### ISSUE THREAD

**Issue by LPeace** [xxgreg/dart_postgresql#74]
Hi I'm wondering why you end the method encodeString(String s) with return " E'$escaped' ";

```
String encodeString(String s) {
  if (s == null) return ' null ';

  var escaped = s.replaceAllMapped(_escapeRegExp, (m) {
   switch (s.codeUnitAt(m.start)) {
     case _apos: return r"\'";
     case _return: return r'\r';
     case _newline: return r'\n';
     case _backslash: return r'\\';
     default: assert(false);
   }
 });

  return " E'$escaped' ";
}
```

Because of the inserted E' my insert command crashes. 

> ERROR 42601 syntax error at or near "E'"ComponentID","Description", ...

**Comment by xxgreg** [comment]
Cheers for the bug report.

I am using postgresql's escaped strings. i.e. select E'fo\no';

http://www.postgresql.org/docs/9.2/static/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE

Any string value passed to query() or execute() should be escaped correctly automatically. Sounds like that isn't happening here. Could you send me a short reproduction of this problem so that I can take a look?

**Comment by LPeace** [comment]
Thanks for the reply.

Here is the code where I execute my Insert 
`return _Execute('INSERT INTO @partType (@columns) VALUES (@rowValues)', {'partType' : partType, 'columns' : columns, 'rowValues' : rowValues});`

At this point the values are :
```
partType = "Diodes"
columns = "\"ComponentID\",\"Description\",\"Library Ref\",\"Library Path\", ..."
rowValues = "'Test','test','','', ..."
```
When the Query is about to get sent this is the query string :

`sql = "INSERT INTO  E'Diodes'  ( E'"ComponentID","Description","Library Ref","Library Path", ...' ) VALUES ( E'\'Test\',\'test\',\'\',\'\', ...' )`

Thanks again for the help!

**Comment by xxgreg** [comment]
Right got it. I should document this better, but the library only supports binding values.

i.e. query("insert into foo values (@a, @b), {'a': 'foo', 'b': 'bar'})

If you'd like to build dynamic queries, i.e. swapping out table names or generating lists then you should use a query building library. Sorry I can't recommend one, I think there are a couple in pub.

Otherwise you will need to very carefully build the query as a string. But beware of SQL injection.

**Comment by LPeace** [comment]
Thanks for the help!

**Comment by xxgreg** [comment]
No problem. Happy to answer questions ;)
